server.port: 9090

spring:
  output:
    ansi:
      enabled: always

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:13306/project-voucher-mysql
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    # spring boot 2.x , hibernate 5.x
   # org.hibernate.type.descriptor.sql.BasicBinder: TRACE


